import { task } from 'hardhat/config';
import { TASK_COMPILE, TASK_CLEAN, TASK_TEST } from 'hardhat/builtin-tasks/task-names';
import type { HardhatRuntimeEnvironment } from 'hardhat/types';

import { poseidonContract } from 'circomlibjs';

/**
 * Overwrites build artifacts to inject generated bytecode
 *
 * @param hre - hardhat runtime environment
 * @param contractName - contract name to overwrite
 * @param bytecode - bytecode to inject
 * @returns promise for completion
 */
async function overwriteArtifact(
  hre: HardhatRuntimeEnvironment,
  contractName: string,
  bytecode: string,
): Promise<void> {
  const artifact = await hre.artifacts.readArtifact(contractName);
  artifact.bytecode = bytecode;
  await hre.artifacts.saveArtifactAndDebugFile(artifact);
}

task(TASK_COMPILE).setAction(async (taskArguments, hre, runSuper) => {
  await runSuper();
  await overwriteArtifact(
    hre,
    'contracts/logic/Poseidon.sol:PoseidonT3',
    poseidonContract.createCode(2),
  );
  await overwriteArtifact(
    hre,
    'contracts/logic/Poseidon.sol:PoseidonT4',
    poseidonContract.createCode(3),
  );
  await hre.run('abi:export');
  await hre.run('storage:export');
});

task(TASK_CLEAN).setAction(async (taskArguments, hre, runSuper) => {
  await runSuper();
  await hre.run('abi:clean');
  await hre.run('storage:clean');
});

task(TASK_TEST, 'Runs test suite')
  .addFlag('skipLongTests', 'Skips or runs shorter versions of long tests')
  .setAction(async (taskArguments: { skipLongTests: string | undefined }, hre, runSuper) => {
    // Set SKIP_LONG_TESTS env to true if flag is set
    if (taskArguments.skipLongTests) process.env.SKIP_LONG_TESTS = 'true';

    await runSuper();
  });
